POST http://localhost:8150/?name=minnan&password=123
Content-Type: application/json
Authorization: Bear aaaa

{
    "name":"asdfasf"
}


###
GET https://api.doctorxiong.club/v1/stock/kline/day?token=LJUjbTGJeO&code=sh600000&startDate=2021-01-01&type=1

###
POST http://minnan.site:2008/stock/getEligibleStockList
Content-Type: application/json
Accept: application/json

{
    "noteDate":"2021-11-26",
    "pageSize":10,
    "pageIndex":2
}