POST {{baseUrl}}/stock/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

> {% client.global.set("token", 'Bearer ' + response.body.data.token) %}


###
GET https://api.doctorxiong.club/v1/stock/kline/day?token=LJUjbTGJeO&code=sh600000&startDate=2021-01-01&type=1

###
POST http://localhost:8150/stock/getEligibleStockList
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
  "noteDate": "2022-03-28",
  "pageSize": 10,
  "pageIndex": 1
}

###
POST http://{{baseUrl}}/stock/getKLineData
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
  "id": 1
}

###
POST {{baseUrl}}/stock/statistics/getMarketLimitLine
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{}

###
POST http://localhost:8151/getAllStock

###
POST http://localhost:8151/getStockPriceHistory
Content-Type: application/json

{
  "stockNickCode": "000001.SZ",
  "startDate": "2022-01-01",
  "endDate": "2022-05-17"
}

###
POST http://localhost:8151/dected
Content-Type: application/json

{
  "date": "20220517"
}

###
GET https://api.doctorxiong.club/v1/stock/kline/day?startDate=2021-01-01&type=1&code=sh000001