server:
  port: 9001
  tomcat:
    accesslog:
      enabled: true

spring:
  application:
    name: api-manager-project
  datasource:
    url: jdbc:mysql://minnan.site:3306/stock?serverTimezone=Asia/Shanghai
    username: Minnan
    password: minnan
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 600000
  redis:
    host: minnan.site
    port: 6379
    database: 3
    password: minnan
  cache:
    type: redis


mybatis-plus:
  mapper-locations: /site/minnan/stock/domain/mapper/*.xml
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

jwt:
  header: Authorization
  expiration: 604800
  secret: min107
  authorized: true

stock:
  priceUrl: https://api.doctorxiong.club/v1/stock/kline/day
  token: LJUjbTGJeO